CREATE DATABASE LIBRARY;
USE LIBRARY;

CREATE TABLE BOOKS(
  BOOK_ID INT PRIMARY KEY,
  BOOK_NAME VARCHAR(100) NOT NULL,
  AUTHOR_NAME VARCHAR(50)
  
);

CREATE TABLE MEMBERS(
MEMBER_ID INT PRIMARY KEY,
 MEMBER_NAME VARCHAR(50) NOT NULL,
 EMAIL VARCHAR(100)
 
 
);

CREATE TABLE BOOK_ISSUED(
  BOOK_ISSUED_ID INT PRIMARY KEY,
  BOOK_ID INT,
  MEMBER_ID INT,
  BOOK_ISSUE_DATE DATE NOT NULL,
  FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
  
);


